export const AUTH_MESSAGE_CONSTANT = {
  PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCHED: "PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCHED",
  INVALID_EMAIL_OR_PASSWORD: "INVALID_EMAIL_OR_PASSWORD",
  EMAIL_ALREADY_TAKEN: "EMAIL_ALREADY_TAKEN",
  USERNAME_ALREADY_TAKEN: "USERNAME_ALREADY_TAKEN",
  UNABLE_SIGNUP_USER: "UNABLE_SIGNUP_USER",
  USER_CREATED_SUCCESSFULLY: "USER_CREATED_SUCCESSFULLY",
  DISABLED_ACCOUNT: "DISABLED_ACCOUNT",
};

export const AUTH_PAYLOAD_VALIDATION_MESSAGE_CONSTANT = {
  FIRST_NAME_MUST_BE_STRING: "FIRST_NAME_MUST_BE_STRING",
  FIRST_NAME_MUST_BE_REQUIRED: "FIRST_NAME_MUST_BE_REQUIRED",

  LAST_NAME_NAME_MUST_BE_STRING: "LAST_NAME_NAME_MUST_BE_STRING",
  LAST_NAME_NAME_MUST_BE_REQUIRED: "FIRST_NAME_MUST_BE_REQUIRED",

  EMAIL_MUST_BE_STRING: "EMAIL_MUST_BE_STRING",
  EMAIL_MUST_BE_REQUIRED: "EMAIL_MUST_BE_REQUIRED",

  USERNAME_MUST_BE_STRING: "USERNAME_MUST_BE_STRING",
  USERNAME_MUST_BE_REQUIRED: "USERNAME_MUST_BE_REQUIRED",

  PASSWORD_MUST_BE_STRING: "PASSWORD_MUST_BE_STRING",
  PASSWORD_MUST_BE_REQUIRED: "PASSWORD_MUST_BE_REQUIRED",

  CONFIRM_PASSWORD_MUST_BE_STRING: "CONFIRM_PASSWORD_MUST_BE_STRING",
  CONFIRM_PASSWORD_MUST_BE_REQUIRED: "CONFIRM_PASSWORD_MUST_BE_REQUIRED",

  ADDRESS_PASSWORD_MUST_BE_STRING: "CONFIRM_PASSWORD_MUST_BE_STRING",
  ADDRESS_PASSWORD_MUST_BE_REQUIRED: "CONFIRM_PASSWORD_MUST_BE_REQUIRED",
};
