export const USER_MESSAGE_CONSTANT = {
  UNABLE_TO_CREATE_USER: "UNABLE_TO_CREATE_USER",
  USER_CREATED_SUCCESSFULLY: "USER_CREATED_SUCCESSFULLY",

  USER_RECORD_NOT_FOUND: "USER_RECORD_NOT_FOUND",
  USER_DETAILS_FETCHED_SUCCESSFULLY: "USER_DETAILS_FETCHED_SUCCESSFULLY",

  USERS_FETCHED_SUCCESSFULLY: "USERS_FETCHED_SUCCESSFULLY",

  UNABLE_TO_UPDATE_USER: "UNABLE_TO_UPDATE_USER",
  USER_UPDATED_SUCCESSFULLY: "USER_UPDATED_SUCCESSFULLY",

  UNABLE_TO_DISABLE_USER: "UNABLE_TO_DISABLE_USER",
  USER_DISABLED_SUCCESSFULLY: "USER_DISABLED_SUCCESSFULLY",

  UNABLE_TO_DELETE_USER: "UNABLE_TO_DELETE_USER",
  USER_DELETED_SUCCESSFULLY: "USER_DELETED_SUCCESSFULLY",

  UNABLE_TO_ENABLE_USER: "UNABLE_TO_ENABLE_USER",
  USER_ENABLED_SUCCESSFULLY: "USER_ENABLED_SUCCESSFULLY",

  EMAIL_ALREADY_TAKEN: "EMAIL_ALREADY_TAKEN",
  USERNAME_ALREADY_TAKEN: "USERNAME_ALREADY_TAKEN",
};

export const USER_PAYLOAD_VALIDATION_MESSAGE_CONSTANT = {
  ID_MUST_BE_STRING: "ID_MUST_BE_STRING",
  ID_MUST_BE_REQUIRED: "ID_MUST_BE_REQUIRED",

  FIRST_NAME_MUST_BE_STRING: "FIRST_NAME_MUST_BE_STRING",
  FIRST_NAME_MUST_BE_REQUIRED: "FIRST_NAME_MUST_BE_REQUIRED",

  LAST_NAME_NAME_MUST_BE_STRING: "LAST_NAME_NAME_MUST_BE_STRING",
  LAST_NAME_NAME_MUST_BE_REQUIRED: "FIRST_NAME_MUST_BE_REQUIRED",

  EMAIL_MUST_BE_STRING: "EMAIL_MUST_BE_STRING",
  EMAIL_MUST_BE_REQUIRED: "EMAIL_MUST_BE_REQUIRED",

  USERNAME_MUST_BE_STRING: "USERNAME_MUST_BE_STRING",
  USERNAME_MUST_BE_REQUIRED: "USERNAME_MUST_BE_REQUIRED",

  ADDRESS_PASSWORD_MUST_BE_STRING: "CONFIRM_PASSWORD_MUST_BE_STRING",
  ADDRESS_PASSWORD_MUST_BE_REQUIRED: "CONFIRM_PASSWORD_MUST_BE_REQUIRED",
};
